### ISSUE TITLE
Documentation fix: External link for cveform in VINCE FAQ is broken

### ISSUE THREAD

**Issue by pepsijeff** [CERTCC/VINCE#1]
Hi Folks,

An external link to the MITRE cveform web application is broken in the wiki content describing reporter FAQs. It incorrectly redirects a user to https://vince-test.cert-dit.org/comm/faq/cveform.mitre.org.

I'm reporting this issue externally as it appears to be a documentation bug fixable by a coordinator and not a code bug for a developer, per se :)

Plus I get so few opportunities to report bugs in our external content these days as it is generally so well produced and tested!

Kind regards,
Jeff

Link(s):
https://vuls.cert.org/confluence/display/VIN/For+Reporters#ForReporters-WilltheCERT/CCgivemeaCVEID?
https://vuls.cert.org/confluence/pages/viewinfo.action?pageId=69074948

Content:
Will the CERT/CC give me a CVE ID?
The CERT/CC may assign CVEs to vulnerabilities that we actively coordinate, but typically only after vendor(s) have declined to do so. Reporters may always request a CVE ID by contacting the CVE Program directly using ```<a class="external-link" href="https://vince-test.cert-dit.org/comm/faq/cveform.mitre.org" rel="nofollow">cveform.mitre.org</a>```, so if you are attempting to obtain a CVE ID for your report, we suggest starting there

**Comment by zmanion** [comment]
Thanks, fixed: https://vuls.cert.org/confluence/pages/diffpagesbyversion.action?pageId=69074948&originalVersion=14&revisedVersion=16
