### ISSUE TITLE
BUG: Vul Note PDF hyperlinks unclickable

### ISSUE THREAD

**Issue by mstrad** [CERTCC/VINCE#111]
Once a vul note is created for a case and saved, the drop down becomes available to save as json, html, and pdf. The PDF button converts the markdown note into a human-readable pdf document. But any hyperlinks that were placed as part of the markdown text (following the pattern: [Hyperlink Text](Hyperlink URL) in the markdown) do not convert into PDF in such a way that the hyperlinks can be clicked on. Instead the Hyperlink Text remains but you cannot click on it and visit the embedded URL.

Alternatively, if a URL is placed in the vul note as is (ex. https://www.google.com) then the link is clickable. But when we try to embed it as [Google](https://www.google.com) then the word **Google** appears but nothing can be clicked.

**Comment by SEI-gstrom** [comment]
The loss of hyperlinks was caused by an issue with an external library used by VINCE for converting vulnerability notes into PDF format. We have a workaround in development that will probably be ready to deploy early next week.

**Comment by sei-vsarvepalli** [comment]
> The loss of hyperlinks was caused by an issue with an external library used by VINCE for converting vulnerability notes into PDF format. We have a workaround in development that will probably be ready to deploy early next week.

Temporary JS file demo is at 
https://raw.githubusercontent.com/sei-vsarvepalli/VINCE/main/jspdf-write-links.js

**Comment by SEI-gstrom** [comment]
Our fix has been pushed to development for a final round of testing. We expect to send it to production on Monday.

**Comment by sei-vsarvepalli** [comment]
Pushed to production and resolved via #114  - Please verify and let us know if PDF links work okay.
