### ISSUE TITLE
Extra newlines in Vuln Note API "public" URLs

### ISSUE THREAD

**Issue by scovetta** [CERTCC/VINCE#14]
Super minor, but I noticed that the URLs in the 'public' section of one of the Vuln Note API endpoints has extra `\r`'s at the end of some of the links.

Example URL: https://kb.cert.org/vuls/api/257161/

![image](https://user-images.githubusercontent.com/732166/115611878-82081680-a29f-11eb-9abd-ef8986c5b7ae.png)

**Comment by sei-eecoff** [comment]
Thanks for reporting this bug. Issue fixed.
