### ISSUE TITLE
Add vendor-specific tracking ID to e-mail notifications for private messages to/from case coordinators

### ISSUE THREAD

**Issue by productcert** [CERTCC/VINCE#20]
When sending private messages for a particular case to/from the case coordinators, there's an e-mail notification for every message being sent - which is good and the same as for any new posts in the case itself.
The small difference is that the notifications for the case posts contain the vendor-specific tracking ID in the subject. But the notifications about private messages don't.

**Comment by sei-vsarvepalli** [comment]
related to #20
