### ISSUE TITLE
COGLoginView class has hard-coded contact email address

### ISSUE THREAD

**Issue by jwoytek** [CERTCC/VINCE#48]
PR #44 replaced generalized language with a hard-coded email address for contact in the COGLoginView class located in cogauth/views.py. This should be parameterized or returned to generalized language.

**Comment by sei-vsarvepalli** [comment]
Hello @jwoytek 

Thanks for reporting these.  The #46, #47 and this issue, hopefully we can roll it all off to one fix. However I am unclear on what the "Merge tags" mean, can you clarify and give more details what exactly is failing?

Thanks
Vijay

**Comment by jwoytek** [comment]
See lines 126 - 130: https://github.com/CERTCC/VINCE/pull/44/commits/6fb0ef9b04cb8171012d18212d71e028d6a77c82#diff-807b59d0b28017d95ac953f81b1d6f61d711865c0ee269c9dbb908d0d163f1ddR126

**Comment by sei-vsarvepalli** [comment]
Ha Thanks..

**Comment by sei-vsarvepalli** [comment]
PR #49 closes this issue. 

Vijay
