### ISSUE TITLE
API requested features

### ISSUE THREAD

**Issue by madcatter24** [CERTCC/VINCE#6]
- publicly available API roadmap for planning purposes
- ability to update vendor status per vulnerability per case
- ability to update vendor statement per vulnerability per case

**Comment by madcatter24** [comment]
directly related to user story in: https://github.com/CERTCC/VINCE/issues/5

**Comment by zmanion** [comment]
Ability for vendor to update status/statement is done: https://vuls.cert.org/confluence/display/VIN/API#API-Updatevendorstatus

**Comment by zmanion** [comment]
API roadmap is on hold pending CVD protocol development.
