### ISSUE TITLE
Implement PDF Button to VulNotes

### ISSUE THREAD

**Issue by INLNate** [CERTCC/VINCE#67]
We'd like to begin development on a PDF button for VINCE notes. Before we begin, we'd like to make sure we are on the right track. Ideally, this button would sit on the VulNote page and allow the user to download a PDF copy of their note with appropriate markings. We'd appreciate any guidance you have for us.

**Comment by Daniel-INL** [comment]
The PDF output would duplicate the attached documents template without the Reviewer table.
[CISA ICS Advisory Template V3_AMBER.docx](https://github.com/CERTCC/VINCE/files/9912647/CISA.ICS.Advisory.Template.V3_AMBER.docx)

**Comment by sei-vsarvepalli** [comment]
It will be good to know the following
1. Is PDF generation by a Coordinator only in the VinceTrack application? Do the Vendors and Reporters also need this feature from VinceComm?  Do unauthorized/anonymous users who visit VincePub (advisory site currently at https://kb.cert.org/vuls) also needs this capability to forward a PDF of a public notice?
2. Does the PDF template be managed in some way as part of a User profile / Browser Profile or just a presented editable dialog like the current Vulnerability notice in Markdown or HTML language?
3. Is the PDF expected to be stored somewhere and expected as a permalink sent to an authorized user who can authenticate and access the notice?

I would recommend jsPDF to do the whole works on the Web browser client that way we keep work off from the server and not bother with any Django Views. 

https://artskydj.github.io/jsPDF/docs/jsPDF.html 

 We have had good luck with jsPDF in generating SSVC output as PDF from our demo site https://democert.org/ssvc/

**Comment by INLNate** [comment]
Those are great questions.

> 1. Ideally this would be the case that only the coordinator would be able to see it in VinceTrack. Currently we don’t see a use-case where Vendors and Reports would need this ability. Anonymous users do not need to view these since they are likely still in the draft stage.
> 2. Yes, the template should be associated with the User Profile like other currently available features.
> 3. At this time, that feature is not needed.

Thanks for also pointing us in the right direction for developing it client side. I’ll take a deeper look at democert.org/ssvc to see what we can use.

**Comment by sei-vsarvepalli** [comment]
Thanks Emily,

The production version 1.50.6 has the HTML download very similar to your recommendation (See image below) to try and resolve issue #66 .  GitHub update to the version 1.50.6 is pending. 

PDF can be added and can be merged like you suggested.  Only guidelines I have from the architecture side is to avoid any server-side PDF generation and depend more on libraries such as jsPDF to format, create and download PDF locally in the Browser client. 

<img width="500" alt="Screen Shot 2022-11-02 at 4 12 36 PM" src="https://user-images.githubusercontent.com/19911912/199593359-45220fed-dfa4-4cd6-a359-3e927022f07b.png">

Thanks
Vijay

**Comment by INLNate** [comment]
Thanks for the input all! 

We will go ahead and move forward with developing out the PDF button utilizing the jsPDF library for client-side processing. I'll keep you updated on our progress.

Thanks,
Nate

**Comment by sei-vsarvepalli** [comment]
PDF implementation may also require a look into rich text editor options.  This could be in stages with the current rich text editor replacement being the second phase.

**Comment by sei-vsarvepalli** [comment]
Resolved with #104
