### ISSUE TITLE
Edit Vulnerability Button "hangs" and does not allow edit

### ISSUE THREAD

**Issue by mstrad** [CERTCC/VINCE#77]
![image](https://user-images.githubusercontent.com/119458704/211619804-e01fa94e-90e5-46d8-a4bd-fb0d3f79b1ff.png)
When in the details of a "vuln" when you go to edit the details from the "Edit Vulnerability" button, the page darkens and the page hangs. The URL does not update, and the edit cannot take place.

**Comment by sei-vsarvepalli** [comment]
That "Edit Vulnerability" button is superfluous - to be removed entirely. Thanks for catching this issue. The pencil icon on the earlier page does "Edit Vulnerability" - this page is focused on CVE Program system data - interactions are intended with System Of Record from CVE Program (Mitre) itself.

**Comment by sei-vsarvepalli** [comment]
https://github.com/idaholab/INL_VINCE to follow up
