### ISSUE TITLE
BUG: "Add Vulnerability" Button doesn't work after adding a vulnerability from a case view

### ISSUE THREAD

**Issue by mstrad** [CERTCC/VINCE#79]
![image](https://user-images.githubusercontent.com/119458704/211622195-b1022036-02cb-47f0-8d6e-8cf088f2f2f2.png)
From a case view move to the Vuln tab.
Click on "Add Vulnerability"
Enter in the appropriate information and save the vulnerability
THIS view that displays after saving a vulnerability has an "Add Vulnerability" button that does not work. The page darkens and hangs. A user has to return to the case view and repeat steps 1-3 to add additional vulnerabilities.

**Comment by sei-vsarvepalli** [comment]
I am going to close this issue @mstrad  we can follow-up further details in INL Repo  https://github.com/idaholab/INL_VINCE if some features expected/needed.
