### ISSUE TITLE
Could this be using a standard open source license?

### ISSUE THREAD

**Issue by pombredanne** [CERTCC/VINCE#84]
The license text starts like the part of an MIT and then goes into something else.
It would be very nice to use a standard open source license. Otherwise, how could your software fit in a proper SBOM using SPDX license ids?
Thank you for your kind consideration!

**Comment by sei-vsarvepalli** [comment]
Hello @pombredanne 

Yeh, sorry our licensing is complicated. But I don't think it is impossible to represent it in SPDX spec (I assume that is the main concern right?)  Just looking at some examples in https://spdx.github.io/spdx-spec/v2.3/package-information/#713-concluded-license-field shows plenty of flexibility. 

Thanks

**Comment by ahouseholder** [comment]
Hi @pombredanne, so one thing we noticed as a result of your inquiry was that we had previously had a copy-and-paste error in our LICENSE.txt. We've corrected that as of PR #93, so thanks for the issue. 

Regarding your broader question, I'm not sure if that copy-and-paste fix alone is sufficient to address your concerns, but it is our intent that this license is compatible with the MIT license in terms of the expectations it places on downstream users.
That said, we recognize that there are a few more words in LICENSE.txt than there are in https://spdx.org/licenses/MIT.html which result from our business requirements. So it's not as simple as pointing at a standard MIT license text, it does require the specific text we provide to be included in any downstream uses.

If you have any specific concerns remaining with the updated LICENSE.txt as it currently stands, we would of course appreciate whatever feedback you could provide so we can take it back to our stakeholders.

**Comment by sei-vsarvepalli** [comment]
Hello @pombredanne, 

Can you confirm that the license is clear enough?

**Comment by pombredanne** [comment]
> Can you confirm that the license is clear enough?

The previous license was odd and uncommon and IMHO not warranted as the MIT additions look like there are just restating the obvious and the law. IMHO it is still odd and uncommon in its new form and contributes mostly to a mild license entropy increase :).
This could have been avoided as I suggested originally.  We will have to track this as a special license in https://github.com/nexB/scancode-toolkit for detection purpose.
