### ISSUE TITLE
Contact approval process enhancements

### ISSUE THREAD

**Issue by ehatleback** [CERTCC/VINCE#94]
Sometimes VINCE doesn't actually start the contact verification process like it should.  During failure times, the cold-call email to ask about the user in question should start the process, but it doesn't; VINCE should take that to be the "Request Authorization" step, but instead, when the ticket arrives for the second authorizer, the button at the top still says "Request Authorization," when in fact it should already be at the "Complete Association" step by that time.  Other times, the button itself does not display on the ticket, necessitating extra navigation and clicks by the analyst to take the next step in the verification process.

Other adjustments that would be positive features to add: 

1. Do not ask for the new applicant to supply an email address for their organization; but instead ask for a url for the organization in question for the initial verifier to consider as a starting place for verifying the contact.
2. Group join requests that are automatically sent to Admins should ping us (with a VINCE Track ticket) if it sits long enough (3 days maybe?) without the existing Admin taking action.
3. Put in a check box for people to check that notes that the current Admin(s) are no longer active in the group.
4. Consolidate the Contact Updates display in the triage area so that multiple contact update approvals can be viewed and approved simultaneously.

**Comment by sei-vsarvepalli** [comment]
User Approval Requests (UAR) workflow to have the following features:

1. New users requesting to become part of a Vendor organization and the Vendor organizations currently does not exist, will have to provide additional information such as web address to validate their PSIRT.
2. New users requesting to become part of a Vendor account, will be routed to the Group Administrator if one is available. If no Group Administrator is available for the Vendor Group, it will be routed to Triage queue as before. The User can also indicate that their current Group Administrator is no longer active which will also route back to Triage queue.
3. If the Group Administrator fails to respond within 3 days, the Triage queue gets the added information about such pending User Approval Requests.

**Comment by sei-vsarvepalli** [comment]
Hopefully the screenshots below are self-explanatory of the process involved in new approval workflows for VINCE account. If a PSIRT is active and has administrators active, they can manage users under their group. All other requests are approved and managed by human review of the Coordinators.

 **New User's view of requesting access to a new Vendor organization or an existing Vendor**
Auto-populate vendors for a new user's search
<img width="360" alt="Auto-populate-relevant-vendors" src="https://user-images.githubusercontent.com/19911912/226439710-cf7e1852-5696-44ae-81cd-48e15bb5d411.png">

On no vendor match, to create a new vendor request additional information of PSIRT
<img width="360" alt="on-no-vendor-match-gather-PSIRT-info" src="https://user-images.githubusercontent.com/19911912/226439930-73e3ca23-bda4-4913-8e43-d8b7652aadd1.png">

On vendor match, send User Approve Request(UAR) to Group Admin and track it

<img width="360" alt="vendor-match-route-request-to-group-admin" src="https://user-images.githubusercontent.com/19911912/226440230-06510169-3d84-429c-9d73-57da302e3ed7.png">

 **If Vendor present and active with a Group Admin, provide a view of the UAR**
<img width="360" alt="UAR-Group-Admin-view" src="https://user-images.githubusercontent.com/19911912/226440478-1b54e16e-9c0f-46d9-8db8-b91a1a23e67a.png">

Approve/Reject window for Group Admin

<img width="360" alt="Approve:Reject Window" src="https://user-images.githubusercontent.com/19911912/226441643-17b7621c-6257-4015-991e-6b493301eefb.png">

**Comment by ahouseholder** [comment]
Is this issue resolved by #95 or is there still more to be done?

**Comment by sei-vsarvepalli** [comment]
This requirement is not completely covered by PR #95 as yet. The fallback portion of launching a ticket for VINCE Coordinators to handle user approvals that were not timely satisfied by a Group Administrator is still pending.

Vijay

**Comment by tschmidtb51** [comment]
> Auto-populate vendors for a new user's search
> <img alt="Auto-populate-relevant-vendors" width="360" src="https://user-images.githubusercontent.com/19911912/226439710-cf7e1852-5696-44ae-81cd-48e15bb5d411.png">

Is that potentially an information leakage issue?

**Comment by sei-vsarvepalli** [comment]
Hello @tschmidtb51 

The data that is being sent to create this autocomplete has just the Vendor names and a privacy protected EUID.  There is nothing more. None of the user's information is part of this. Any registered user, who has been approved to have an account, can potentially enumerate and know all the vendors who take part in a VINCE coordination platform instance. 

Currently the same things is possible even for unauthenticated users to view all the vendors who are active and have ever participated in a Case - just the Vendor's name. The vincepub UI and search capabilities `autocomplete` lists does something very similar.

https://github.com/CERTCC/VINCE/blob/9728c0533523075137df7c8066d701f685b24716/vincepub/views.py#L1397-L1401

**Comment by sei-vsarvepalli** [comment]
Resolved with #114
